version: '3'

services:
   db:
     image: postgres:9.6.8-alpine
     ports: 
       - 5432
     volumes:
       - /opt/db_data:/var/lib/postgresql/data
     restart: always
     environment:
       POSTGRES_PASSWORD: example
       POSTGRES_USER: postgres
       POSTGRES_DB: mydatabase
       NETWORK: network
     networks:
       - ${NETWORK}

   tomcat:
     image: localhost:5000/rkastomcat
     ports: 
       - "8080:8080"
     environment:
        NETWORK: network
     volumes: 
       - /opt/rkastomcat/projektid:/opt/tomcat/webapps
     links: 
       - db
     networks:
       - ${NETWORK}
networks:
  ${NETWORK}
    external: true

