version: '3'

services:
   db:
     image: postgres:9.6.8-alpine
     ports: 
       - 5432
     volumes:
       - /opt/db_data:/var/lib/postgresql/data
     restart: always
     deploy:
       placement:
         constraints: [node.role == worker]
     environment:
       POSTGRES_PASSWORD: example
       POSTGRES_USER: postgres
   tomcat:
     image: localhost:5000/rkastomcat
     ports: 
       - "8080:8080"
     volumes: 
       - /opt/rkastomcat/projektid:/opt/tomcat/webapps
     links: 
       - db
     deploy:
       placement:
         constraints: [node.role == manager]