version: '3'
services:
   db:
     image: postgres:9.6-alpine
     deploy:
       restart_policy:
         condition: on-failure
     ports: 
       - 5432
     environment:
       POSTGRES_PASSWORD: example
       POSTGRES_USER: postgres
       POSTGRES_DB: mydatabase
     volumes:
       - /opt/db_data:/var/lib/postgresql/data
   tomcat:
     image: centos:5000/rkastomcat
     ports: 
       - "8080:8080"
     volumes: 
       - /opt/rkastomcat/projektid:/opt/tomcat/webapps
